# Generated by Django 3.1.7 on 2021-03-12 23:33

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.embeds.blocks
import wagtail.images.blocks
import wagtailvideos.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210312_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcepage',
            name='content',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock()), ('paragraph', wagtail.core.blocks.RichTextBlock()), ('embed', wagtail.embeds.blocks.EmbedBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('video', wagtailvideos.blocks.VideoChooserBlock())]),
        ),
    ]
