# Generated by Django 3.1.7 on 2021-03-13 02:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0008_auto_20210312_2328'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', tinymce.models.HTMLField()),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='home.activitypage')),
                ('response_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='home.post')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='coursecomment',
            name='page',
        ),
        migrations.RemoveField(
            model_name='coursecomment',
            name='user',
        ),
        migrations.DeleteModel(
            name='ActivityComment',
        ),
        migrations.DeleteModel(
            name='CourseComment',
        ),
    ]
