# Generated by Django 3.1.7 on 2021-03-15 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20210313_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='response_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='home.post'),
        ),
    ]
